version: '3.8'
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  web:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - storage-data:/data/storage
  worker:
    build: ./backend
    env_file: .env
    command: ["sh", "-c", "python worker.py"]
    depends_on:
      - redis
    volumes:
      - storage-data:/data/storage
volumes:
  storage-data:
